ntrip_client:
  ntrip_client_node:
    ros__parameters:
      host: 20.185.11.35
      port: 2101
      mountpoint: VTRI_RTCM3

      ntrip_version: None
      
      authenticate: True
      
      username: user
      password: pass
      
      ssl: False
      
      cert: None
      key: None
      
      ca_cert: None
      
      
      rtcm_frame_id: rover
      
      nmea_max_length: 82
      nmea_min_length: 3
      
      rtcm_message_package: rtcm_msgs
      
      reconnect_attempt_max: 10
      reconnect_attempt_wait_seconds: 5
      
      rtcm_timeout_seconds: 4

